// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtv2U5utRNIot8juD73PpLSs0pkxgcFg8',
    appId: '1:851862176441:web:a77051d1b9fa8e0b981168',
    messagingSenderId: '851862176441',
    projectId: 'note-app-16',
    authDomain: 'note-app-16.firebaseapp.com',
    storageBucket: 'note-app-16.appspot.com',
    measurementId: 'G-TYNGHPFQES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMb4YQweaIe_kmbS1MQC3F8FW7n8bqg_s',
    appId: '1:851862176441:android:b7775ec68fbe0fd1981168',
    messagingSenderId: '851862176441',
    projectId: 'note-app-16',
    storageBucket: 'note-app-16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGTobrg__BWABZdnGPSxcpVD59tQSiW5M',
    appId: '1:851862176441:ios:10d877a83cb908f2981168',
    messagingSenderId: '851862176441',
    projectId: 'note-app-16',
    storageBucket: 'note-app-16.appspot.com',
    iosBundleId: 'com.noteapp.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGTobrg__BWABZdnGPSxcpVD59tQSiW5M',
    appId: '1:851862176441:ios:3bdae611e26b6733981168',
    messagingSenderId: '851862176441',
    projectId: 'note-app-16',
    storageBucket: 'note-app-16.appspot.com',
    iosBundleId: 'com.noteapp.noteApp.RunnerTests',
  );
}
